### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by vermiculus**

### CODE REVIEW

**Comment by kotfic** [comment]
@vermiculus LGTM - I am not currently working on any mumps based projects.  you're welcome to take over this project if you like!

**Comment by vermiculus** [comment]
I can take it off your hands if you'd like 😄

**Comment by kotfic** [comment]
@vermiculus Great!  You'll just have to temporarily remove vermiculus/emacs-mumps so I can transfer the repository. cheers!

**Comment by vermiculus** [comment]
Done.

**Pull request merged**
